# Generated by Django 4.0.5 on 2022-06-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('tipo', models.CharField(max_length=55)),
                ('categoria', models.CharField(max_length=55)),
                ('informacion', models.CharField(max_length=255)),
                ('fuente', models.CharField(max_length=255)),
                ('img', models.ImageField(blank='', default='', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True)),
                ('clave', models.CharField(max_length=60)),
                ('admin', models.BooleanField(default=False)),
                ('icono', models.ImageField(blank='', default='', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=55)),
                ('texto', models.CharField(max_length=255)),
                ('img', models.ImageField(blank='', default='', upload_to='img/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=100)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
