# Generated by Django 4.0.5 on 2022-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='icono',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
