# Generated by Django 4.0.5 on 2022-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='informacion',
            field=models.TextField(),
        ),
    ]
