# Generated by Django 4.0.5 on 2022-07-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_planta_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='fuente',
            field=models.TextField(),
        ),
    ]
