# Generated by Django 4.0.5 on 2022-07-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_planta_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='texto',
            field=models.TextField(),
        ),
    ]
